version: "3.9"
services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: archetype
      POSTGRES_PASSWORD: archetype
      POSTGRES_DB: archetype
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
